provider_name         = "AWS"
atlas_region          = "US_EAST_1"
acceptor_region_name  = "US_EAST_1"
atlas_org_id          = "65e24d75b0bbab5dbe0ebe25"
environment           = "dev"
altas_region          = "US_EAST_1"
ip_address            = "86.139.204.225"